###
GET http://127.0.0.1:8000/api/messages
###
GET http://127.0.0.1:8000/api/messages/id
### 
GET http://127.0.0.1:8000/api/messages/recherche/texte 
###
POST http://127.0.0.1:8000/api/messages
###
PUT http://127.0.0.1:8000/api/messages/id
###
DELETE http://127.0.0.1:8000/api/messages/id

Content-Type:  application/json
###
